### PR TITLE
Added tzinfo to requestContext fields

### PR DESCRIPTION
**Pull request by winguru**
Dieter,

Here are some changes which seem to correct the missing timezone behavior of the smartSummarize function.
1. I added the tzinfo as a value to the requestContext dictionary in app.py.  
2. I used this tzinfo in functions.py to add tzinfo to the smartSummarize function.
3. I also noticed that some datapoints (usually the last one in my experience) are missing timestamp data in the smartSummarize function, so I added a quick check to ensure they are present.

This bug is discussed here:
https://github.com/brutasse/graphite-api/issues/51

I'm not sure the best method to help contributing with this issue, so forgive my ignorance...

### CODE REVIEW

**Comment by Dieterbe** [comment]
so this is something for @brutasse to have a look at because his version is the "official upstream", and ideally your patch goes in there.

**Comment by winguru** [comment]
Thanks Dieter!

I wasn't sure about contacting @brutasse since I'm using InfluxDB as the backend, rather than graphite. I used your support-templates2 branch and have had very good success with it so far ;-)

I will see if I can create an upstream patch...

**Comment by Dieterbe** [comment]
right, but this looks independent of all influxdb/templates stuff, right? if it gets merged there i'll pull it in here ;)
protip: make sure your changes are only about the thing you actually want to fix.  I see you committed some changes to the readme that are personal and shouldn't go into the tzinfo PR. (you can use git rebase and `git add -p` to your advantage)

**Comment by winguru** [comment]
Thanks again for the helpful tips... I am not used to collaborating with others via github, so I appreciate the advice ;-)

I was trying to get Travis-CI testing to pass successfully and wasn't sure the best way to do that.  It was failing with lots of DeprecationWarnings in the setuptools library.  So I was playing around trying to test various ways of ignoring just the warnings within setuptools.

In hindsight, maybe forking another branch just for testing the Travis-CI and unittest scripts would have been wizer ;-)

**Comment by winguru** [comment]
Bruno just accepted the code changes into master.

Thanks again for all your help and advice!!

--Geoff Thornton

**Pull request closed without merging**
